Thu Dec 16 10:26:36 ICT 2021 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
----------------------------------------------------------------
Thu Dec 16 10:26:36 ICT 2021:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-017d-c147-0457-ffff92b2cf61 
on database directory D:\Project OOP\GUI\myDataBase\myDatabase with class loader sun.misc.Launcher$AppClassLoader@6f94fa3e 
Loaded from file:/C:/Program%20Files/Java/jdk1.8.0_111/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Program Files\Java\jdk1.8.0_111\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=D:\Project OOP\GUI\myDataBase
Database Class Loader started - derby.database.classpath=''
Thu Dec 16 11:31:45 ICT 2021 Thread[DRDAConnThread_2,5,main] (XID = 706), (SESSIONID = 1), (DATABASE = myDatabase), (DRDAID = ????????.????-797135494419380875{1}), Cleanup action starting
Thu Dec 16 11:31:45 ICT 2021 Thread[DRDAConnThread_2,5,main] (XID = 706), (SESSIONID = 1), (DATABASE = myDatabase), (DRDAID = ????????.????-797135494419380875{1}), Failed Statement is: null with 4 parameters begin parameter #1: % :end parameter begin parameter #2: MYJDB :end parameter begin parameter #3: PRODUCT :end parameter begin parameter #4: % :end parameter 
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.remove(ArrayList.java:495)
	at org.apache.derby.iapi.services.context.ContextManager.popContext(Unknown Source)
	at org.apache.derby.iapi.services.context.ContextImpl.popMe(Unknown Source)
	at org.apache.derby.impl.store.access.RAMTransaction.destroy(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.doRollback(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.userRollback(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.rollback(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.rollback(Unknown Source)
	at org.apache.derby.impl.drda.Database.close(Unknown Source)
	at org.apache.derby.impl.drda.Session.close(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.closeSession(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Cleanup action completed
Thu Dec 16 11:31:45 ICT 2021 Thread[DRDAConnThread_2,5,main] (DATABASE = myDatabase), (DRDAID = ????????.????-797135494419380875{1}), Java exception: '-1: java.lang.ArrayIndexOutOfBoundsException'.
Thu Dec 16 11:31:45 ICT 2021 : Java exception: '-1: java.lang.ArrayIndexOutOfBoundsException'.
java.sql.SQLException: Java exception: '-1: java.lang.ArrayIndexOutOfBoundsException'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.javaException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.rollback(Unknown Source)
	at org.apache.derby.impl.drda.Database.close(Unknown Source)
	at org.apache.derby.impl.drda.Session.close(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.closeSession(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR XJ001: Java exception: '-1: java.lang.ArrayIndexOutOfBoundsException'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 12 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.remove(ArrayList.java:495)
	at org.apache.derby.iapi.services.context.ContextManager.popContext(Unknown Source)
	at org.apache.derby.iapi.services.context.ContextImpl.popMe(Unknown Source)
	at org.apache.derby.impl.store.access.RAMTransaction.destroy(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.doRollback(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.userRollback(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.rollback(Unknown Source)
	... 5 more
Thu Dec 16 11:31:45 ICT 2021 Thread[DRDAConnThread_2,5,main] (DATABASE = myDatabase), (DRDAID = ????????.????-797135494419380875{1}), Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = myDatabase; diagnostic msg = Java exception: '-1: java.lang.ArrayIndexOutOfBoundsException'.
Thu Dec 16 11:31:45 ICT 2021 : Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = myDatabase; diagnostic msg = Java exception: '-1: java.lang.ArrayIndexOutOfBoundsException'.
org.apache.derby.impl.drda.DRDAProtocolException: Execution failed because of Permanent Agent Error: SVRCOD = 40; RDBNAM = myDatabase; diagnostic msg = Java exception: '-1: java.lang.ArrayIndexOutOfBoundsException'.
	at org.apache.derby.impl.drda.DRDAProtocolException.newAgentError(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.sendUnexpectedException(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.closeSession(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
----------------------------------------------------------------
Thu Dec 16 11:31:45 ICT 2021: Shutting down Derby engine
